global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "target-node"
    static_configs:
      - targets: ["<TARGET_NODE_IP>:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["127.0.0.1:9093"]
