global:
  resolve_timeout: 5m

route:
  receiver: "webhook_receiver"

receivers:
  - name: "webhook_receiver"
    webhook_configs:
      - url: "http://<webhook_script_endpoint_IP>:5001/webhook"   # your webhook script endpoint
